export const TASKS_LIST_REQUEST = 'TASKS_LIST_REQUEST';
export const TASKS_LIST_SUCCESS = 'TASKS_LIST_SUCCESS';
export const TASKS_LIST_FAIL = 'TASKS_LIST_FAIL';
export const TASKS_LIST_ERROR = 'TASKS_LIST_ERROR';

//export const SINGLE_TASK_REQUEST = 'SINGLE_TASK_REQUEST';
export const SINGLE_TASK_SUCCESS = 'SINGLE_TASK_SUCCESS';
// export const SINGLE_TASK_FAIL = 'SINGLE_TASK_FAIL';
// export const SINGLE_TASK_ERROR = 'SINGLE_TASK_ERROR';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
export const TASK_DELETE_ERROR = 'TASK_DELETE_ERROR';

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';
export const TASK_CREATE_ERROR = 'TASK_CREATE_ERROR';

export const TASK_EDIT_REQUEST = 'TASK_EDIT_REQUEST';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_FAIL = 'TASK_EDIT_FAIL';
export const TASK_EDIT_ERROR = 'TASK_EDIT_ERROR';
export const TASK_EDIT_CANCEL = 'TASK_EDIT_ERROR';
